#
# Image Batch Extend With RIFE — finds a gradient-MSE boundary, applies the
# existing pyramid transition, and optionally replaces its center with RIFE
# frames generated by the installed ComfyUI-Frame-Interpolation provider.
#

import math
from typing import Optional

import torch  # type: ignore
import torch.nn.functional as F  # type: ignore

from comfy_api.latest import io  # type: ignore
from ..core import CATEGORY
from ..core.image_helpers import cat_and_fit_images, flatten_images, unwrap_value
from ..core.logger import log


_LOG_PREFIX = "ImageBatchExtendWithRife"
_MATCH_DOWNSAMPLE_SIZE = 512
_OVERLAP_SIDE_OPTIONS = ["source", "new_images", "both"]
_RIFE_MODEL_OPTIONS = [
    "none",
    "rife47.pth",
    "rife49.pth",
    "rife417.pth",
    "rife426.pth",
    "sudo_rife4_269.662_testV1_scale1.pth",
]


def _find_gradient_match(
    source: torch.Tensor, new_images: torch.Tensor, search_frames: int, side: str
) -> tuple[int, int, float]:
    # Find the structurally closest source/new pair using gradient-magnitude MSE.
    n_src, n_new = source.shape[0], new_images.shape[0]
    search_n_src = max(1, min(search_frames, n_src))
    search_n_new = max(1, min(search_frames, n_new))
    if side == "source":
        src_start, new_end = max(0, n_src - search_n_src), 1
    elif side == "new_images":
        src_start, new_end = n_src - 1, min(n_new, search_n_new)
    else:
        src_start, new_end = max(0, n_src - search_n_src), min(n_new, search_n_new)

    height = min(source.shape[1], new_images.shape[1])
    width = min(source.shape[2], new_images.shape[2])
    scale = _MATCH_DOWNSAMPLE_SIZE / max(height, width)
    target_size = (max(1, round(height * scale)), max(1, round(width * scale)))
    src_ds = F.interpolate(
        source[src_start:, ..., :3].permute(0, 3, 1, 2).float(),
        size=target_size,
        mode="bilinear",
        align_corners=False,
    )
    new_ds = F.interpolate(
        new_images[:new_end, ..., :3].permute(0, 3, 1, 2).float(),
        size=target_size,
        mode="bilinear",
        align_corners=False,
    )

    def gradient_magnitude(images: torch.Tensor) -> torch.Tensor:
        dx = images[:, :, :, 1:] - images[:, :, :, :-1]
        dy = images[:, :, 1:, :] - images[:, :, :-1, :]
        return (dx[:, :, :-1, :].pow(2) + dy[:, :, :, :-1].pow(2)).sqrt().mean(dim=1)

    src_features = gradient_magnitude(src_ds).flatten(1)
    new_features = gradient_magnitude(new_ds).flatten(1)
    feature_count = src_features.shape[1]
    scores = (
        src_features.pow(2).sum(dim=1).unsqueeze(1)
        + new_features.pow(2).sum(dim=1).unsqueeze(0)
        - 2 * (src_features @ new_features.T)
    ) / feature_count
    flat_index = int(scores.argmin().item())
    src_index, new_index = divmod(flat_index, new_features.shape[0])
    return src_start + src_index, new_index, float(scores[src_index, new_index].item())


def _pyramid_blend(src: torch.Tensor, dst: torch.Tensor, alpha: torch.Tensor) -> torch.Tensor:
    # Blend frequency bands separately while avoiding invalid pyramid levels on small images.
    src_float = src.float().permute(0, 3, 1, 2)
    dst_float = dst.float().permute(0, 3, 1, 2)
    levels = max(1, min(4, int(math.log2(min(src.shape[1], src.shape[2]))) + 1))

    def laplacian(images: torch.Tensor) -> list[torch.Tensor]:
        gaussian = [images]
        for _ in range(levels - 1):
            gaussian.append(F.avg_pool2d(gaussian[-1], kernel_size=2, stride=2))
        bands = []
        for index in range(levels - 1):
            upsampled = F.interpolate(
                gaussian[index + 1],
                size=gaussian[index].shape[2:],
                mode="bilinear",
                align_corners=False,
            )
            bands.append(gaussian[index] - upsampled)
        bands.append(gaussian[-1])
        return bands

    blended_bands = [
        (1 - alpha) * src_band + alpha * dst_band
        for src_band, dst_band in zip(laplacian(src_float), laplacian(dst_float))
    ]
    result = blended_bands[-1]
    for band in reversed(blended_bands[:-1]):
        result = F.interpolate(
            result, size=band.shape[2:], mode="bilinear", align_corners=False
        ) + band
    return result.permute(0, 2, 3, 1).to(src.dtype)


def _resize_to_match(images: torch.Tensor, target_height: int, target_width: int) -> torch.Tensor:
    # Scale to fill, then center-crop, matching Image Batch Extend With Overlap.
    height, width = images.shape[1:3]
    if (height, width) == (target_height, target_width):
        return images
    scale = max(target_width / width, target_height / height)
    scaled_width = max(round(width * scale), target_width)
    scaled_height = max(round(height * scale), target_height)
    resized = F.interpolate(
        images.movedim(-1, 1),
        size=(scaled_height, scaled_width),
        mode="bilinear",
        align_corners=False,
    ).movedim(1, -1)
    x_offset = (scaled_width - target_width) // 2
    y_offset = (scaled_height - target_height) // 2
    return resized[:, y_offset : y_offset + target_height, x_offset : x_offset + target_width]


def _generate_rife_frames(
    endpoints: torch.Tensor,
    rife_model: str,
    frame_count: int,
    fast_mode: bool,
    ensemble: bool,
    scale_factor: float,
) -> Optional[torch.Tensor]:
    # Invoke the registered RIFE provider without importing another custom-node module.
    if frame_count < 1:
        return None
    try:
        import nodes  # type: ignore

        rife_class = nodes.NODE_CLASS_MAPPINGS.get("RIFE VFI")
        if rife_class is None:
            raise RuntimeError("RIFE VFI is not registered")
        result = rife_class().vfi(
            ckpt_name=rife_model,
            frames=endpoints,
            multiplier=frame_count + 1,
            fast_mode=fast_mode,
            ensemble=ensemble,
            scale_factor=scale_factor,
        )
        generated = result[0] if isinstance(result, tuple) else result
        if not isinstance(generated, torch.Tensor) or generated.shape[0] != frame_count + 2:
            raise RuntimeError("RIFE returned an unexpected frame count")
        return generated[1:-1].to(device=endpoints.device, dtype=endpoints.dtype)
    except Exception as error:
        log.warning(
            _LOG_PREFIX,
            f"RIFE refinement unavailable ({error}); keeping the pyramid transition.",
        )
        return None


class RvImage_BatchExtendWithRife(io.ComfyNode):
    @classmethod
    def define_schema(cls):
        return io.Schema(
            node_id="Image Batch Extend With RIFE [Eclipse]",
            display_name="Image Batch Extend With RIFE",
            category=CATEGORY.MAIN.value + CATEGORY.IMAGE_BATCH.value,
            description=(
                "Matches the source/new boundary with gradient-MSE, creates the same pyramid blend "
                "as match_gradient_mse+pyramid, and optionally replaces its center with RIFE frames. "
                "Select none for the unchanged pyramid-only transition."
            ),
            inputs=[
                io.Image.Input("source_images", optional=True),
                io.Int.Input(
                    "overlap",
                    default=5,
                    min=0,
                    max=4096,
                    step=1,
                    tooltip="Match search and pyramid-blend window length. 0 concatenates the batches.",
                ),
                io.Combo.Input(
                    "overlap_side",
                    options=_OVERLAP_SIDE_OPTIONS,
                    default="both",
                    tooltip="Select whether the source tail, new head, or both are searched for the match.",
                ),
                io.Combo.Input(
                    "rife_model",
                    options=_RIFE_MODEL_OPTIONS,
                    default="none",
                    tooltip="RIFE checkpoint from ComfyUI-Frame-Interpolation. none keeps the pyramid blend unchanged.",
                ),
                io.Int.Input(
                    "rife_transition_frames",
                    default=3,
                    min=0,
                    max=4,
                    step=1,
                    tooltip="Number of center blend frames replaced by RIFE. The output length is unchanged.",
                ),
                io.Boolean.Input("rife_fast_mode", default=True),
                io.Boolean.Input("rife_ensemble", default=False),
                io.Float.Input("rife_scale_factor", default=1.0, min=0.25, max=4.0, step=0.25),
                io.Image.Input("new_images", optional=True),
            ],
            outputs=[io.Image.Output("images")],
            is_input_list=True,
        )

    @classmethod
    def execute(
        cls,
        overlap,
        overlap_side,
        rife_model,
        rife_transition_frames,
        rife_fast_mode,
        rife_ensemble,
        rife_scale_factor,
        source_images=None,
        new_images=None,
    ):
        overlap = unwrap_value(overlap, 5)
        overlap_side = unwrap_value(overlap_side, "both")
        rife_model = unwrap_value(rife_model, "none")
        rife_transition_frames = unwrap_value(rife_transition_frames, 3)
        rife_fast_mode = unwrap_value(rife_fast_mode, True)
        rife_ensemble = unwrap_value(rife_ensemble, False)
        rife_scale_factor = unwrap_value(rife_scale_factor, 1.0)
        flat_source, flat_new = flatten_images(source_images), flatten_images(new_images)
        if not flat_source and not flat_new:
            raise ValueError("At least one image batch must be connected.")
        if not flat_source:
            return io.NodeOutput(cat_and_fit_images(flat_new, log_prefix=_LOG_PREFIX))
        if not flat_new:
            return io.NodeOutput(cat_and_fit_images(flat_source, log_prefix=_LOG_PREFIX))

        source = cat_and_fit_images(flat_source, log_prefix=_LOG_PREFIX)
        new = cat_and_fit_images(flat_new, log_prefix=_LOG_PREFIX)
        if source is None or new is None:
            return io.NodeOutput(None)
        if source.shape[1:3] != new.shape[1:3]:
            new = _resize_to_match(new, source.shape[1], source.shape[2])
        if overlap == 0:
            return io.NodeOutput(torch.cat((source, new), dim=0))

        try:
            source_cut, new_cut, score = _find_gradient_match(source, new, overlap, overlap_side)
            blend_length = min(overlap, len(source) - source_cut, len(new) - new_cut)
            blend_source = source[source_cut : source_cut + blend_length]
            blend_new = new[new_cut : new_cut + blend_length]
            alpha = torch.linspace(
                0, 1, blend_length + 2, device=source.device, dtype=source.dtype
            )[1:-1].view(-1, 1, 1, 1)
            blended = _pyramid_blend(blend_source, blend_new, alpha)
            refine_count = min(rife_transition_frames, max(0, blend_length - 2))
            if rife_model != "none" and refine_count:
                replace_start = (blend_length - refine_count) // 2
                endpoints = torch.cat(
                    (
                        blend_source[replace_start - 1 : replace_start],
                        blend_new[replace_start + refine_count : replace_start + refine_count + 1],
                    ),
                    dim=0,
                )
                rife_frames = _generate_rife_frames(
                    endpoints,
                    rife_model,
                    refine_count,
                    rife_fast_mode,
                    rife_ensemble,
                    rife_scale_factor,
                )
                if rife_frames is not None:
                    blended[replace_start : replace_start + refine_count] = rife_frames
            log.msg(
                _LOG_PREFIX,
                f"Gradient match: src={source_cut}, new={new_cut}, score={score:.5f}, "
                f"blend={blend_length}, RIFE={rife_model}.",
            )
            return io.NodeOutput(
                torch.cat((source[:source_cut], blended, new[new_cut + blend_length :]), dim=0)
            )
        except Exception as error:
            log.warning(_LOG_PREFIX, f"Transition failed, falling back to concat: {error}")
            return io.NodeOutput(torch.cat((source, new), dim=0))